#name: Run tests on PR
#
#on:
#  pull_request:
#    branches:
#      - dev
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Run tests
#        run: |
#          cd backend
#          docker compose -f docker-compose.test.yml run web-test || exit 1
#          docker compose -f docker-compose.test.yml down -v --remove-orphans
#
